from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AIResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, generated_text=None):  # noqa: E501
        """AIResponse - a model defined in OpenAPI

        :param generated_text: The generated_text of this AIResponse.  # noqa: E501
        :type generated_text: str
        """
        self.openapi_types = {
            'generated_text': str
        }

        self.attribute_map = {
            'generated_text': 'generatedText'
        }

        self._generated_text = generated_text

    @classmethod
    def from_dict(cls, dikt) -> 'AIResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AIResponse of this AIResponse.  # noqa: E501
        :rtype: AIResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def generated_text(self) -> str:
        """Gets the generated_text of this AIResponse.


        :return: The generated_text of this AIResponse.
        :rtype: str
        """
        return self._generated_text

    @generated_text.setter
    def generated_text(self, generated_text: str):
        """Sets the generated_text of this AIResponse.


        :param generated_text: The generated_text of this AIResponse.
        :type generated_text: str
        """
        if generated_text is None:
            raise ValueError("Invalid value for `generated_text`, must not be `None`")  # noqa: E501

        self._generated_text = generated_text
