from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GenerateResponseForRawNoteRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, note_id=None, prompt=None):  # noqa: E501
        """GenerateResponseForRawNoteRequest - a model defined in OpenAPI

        :param note_id: The note_id of this GenerateResponseForRawNoteRequest.  # noqa: E501
        :type note_id: str
        :param prompt: The prompt of this GenerateResponseForRawNoteRequest.  # noqa: E501
        :type prompt: str
        """
        self.openapi_types = {
            'note_id': str,
            'prompt': str
        }

        self.attribute_map = {
            'note_id': 'noteId',
            'prompt': 'prompt'
        }

        self._note_id = note_id
        self._prompt = prompt

    @classmethod
    def from_dict(cls, dikt) -> 'GenerateResponseForRawNoteRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The generateResponseForRawNote_request of this GenerateResponseForRawNoteRequest.  # noqa: E501
        :rtype: GenerateResponseForRawNoteRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note_id(self) -> str:
        """Gets the note_id of this GenerateResponseForRawNoteRequest.


        :return: The note_id of this GenerateResponseForRawNoteRequest.
        :rtype: str
        """
        return self._note_id

    @note_id.setter
    def note_id(self, note_id: str):
        """Sets the note_id of this GenerateResponseForRawNoteRequest.


        :param note_id: The note_id of this GenerateResponseForRawNoteRequest.
        :type note_id: str
        """

        self._note_id = note_id

    @property
    def prompt(self) -> str:
        """Gets the prompt of this GenerateResponseForRawNoteRequest.


        :return: The prompt of this GenerateResponseForRawNoteRequest.
        :rtype: str
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt: str):
        """Sets the prompt of this GenerateResponseForRawNoteRequest.


        :param prompt: The prompt of this GenerateResponseForRawNoteRequest.
        :type prompt: str
        """

        self._prompt = prompt
