openapi: 3.0.3
info:
  title: Thinkify - OpenAPI 3.0
  version: 1.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://thinkify.giolom.com/api/v1
tags:
- description: retrieving note information
  name: note
- description: ai operations
  name: ai
- description: cors support
  name: cors
paths:
  /ai/generateResponseForRawNote/{noteId}:
    options:
      description: |
        Enable CORS by returning correct headers
      operationId: ai_generate_response_cors
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content: {}
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Methods:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Headers:
              explode: false
              schema:
                type: string
              style: simple
      summary: CORS support
      tags:
      - cors
      x-openapi-router-controller: openapi_server.controllers.cors_controller
    post:
      description: raw note is taken as input
      operationId: generate_response_for_raw_note
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/generateResponseForRawNote_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: AI response
        "400":
          description: Invalid status value
      summary: Generate an AI response based on a raw note and prompt
      tags:
      - ai
      x-openapi-router-controller: openapi_server.controllers.ai_controller
  /ai/transcribeAudioForNote/{noteId}:
    options:
      description: |
        Enable CORS by returning correct headers
      operationId: ai_transcribe_cors
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content: {}
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Methods:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Headers:
              explode: false
              schema:
                type: string
              style: simple
      summary: CORS support
      tags:
      - cors
      x-openapi-router-controller: openapi_server.controllers.cors_controller
    post:
      description: "Take an audio file and transcribe it, so we have a textual representation\
        \ of its content"
      operationId: transcribe_audio_for_note
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/transcribeAudioForNote_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                example: This is a transcription
                type: string
          description: transcription string
        "400":
          description: Invalid status value
      summary: Transcribe an audio file
      tags:
      - ai
      x-openapi-router-controller: openapi_server.controllers.ai_controller
  /note/list:
    get:
      description: Array of all notes
      operationId: get_all_notes
      responses:
        "202":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NoteMetaData'
                type: array
          description: Created
        "404":
          description: Some bricks or tenants not found
      summary: Retrieve list of all notes
      tags:
      - note
      x-openapi-router-controller: openapi_server.controllers.note_controller
  /note/new:
    options:
      description: |
        Enable CORS by returning correct headers
      operationId: new_note_cors
      responses:
        "200":
          content: {}
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Methods:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Headers:
              explode: false
              schema:
                type: string
              style: simple
      summary: CORS support
      tags:
      - cors
      x-openapi-router-controller: openapi_server.controllers.cors_controller
    put:
      description: Adds new note object to database
      operationId: create_new_note
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                type: string
          description: Created
      summary: put new note object
      tags:
      - note
      x-openapi-router-controller: openapi_server.controllers.note_controller
  /note/{noteId}:
    get:
      description: Full note object with all attributes
      operationId: get_note_by_id
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
          description: Created
        "404":
          description: note not found
      summary: Get one single note by id
      tags:
      - note
      x-openapi-router-controller: openapi_server.controllers.note_controller
    options:
      description: |
        Enable CORS by returning correct headers
      operationId: note_cors
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content: {}
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Methods:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Headers:
              explode: false
              schema:
                type: string
              style: simple
      summary: CORS support
      tags:
      - cors
      x-openapi-router-controller: openapi_server.controllers.cors_controller
    post:
      description: Full note object with all attributes
      operationId: update_note_by_id
      parameters:
      - description: "the note identifier, as noteId"
        explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
          description: Updated
        "404":
          description: note not found
      summary: patch note object
      tags:
      - note
      x-openapi-router-controller: openapi_server.controllers.note_controller
components:
  parameters:
    noteId:
      description: "the note identifier, as noteId"
      explode: false
      in: path
      name: noteId
      required: true
      schema:
        type: string
      style: simple
  responses:
    cors:
      content: {}
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Origin:
          explode: false
          schema:
            type: string
          style: simple
        Access-Control-Allow-Methods:
          explode: false
          schema:
            type: string
          style: simple
        Access-Control-Allow-Headers:
          explode: false
          schema:
            type: string
          style: simple
  schemas:
    AbstractEntity:
      properties:
        id:
          example: 1
          title: id
          type: integer
        createdAt:
          example: 2024-01-01T13:10:28Z
          format: date-time
          title: createdAt
          type: string
        updatedAt:
          example: 2024-01-01T15:22:44Z
          format: date-time
          title: updatedAt
          type: string
      title: AbstractEntity
      type: object
    NoteMetaData:
      allOf:
      - $ref: '#/components/schemas/AbstractEntity'
      - properties:
          name:
            example: Note1
            type: string
        type: object
      title: NoteMetaData
    Note:
      allOf:
      - $ref: '#/components/schemas/NoteMetaData'
      - properties:
          rawText:
            example: This is the transcript of an audio record
            type: string
          aiOutput:
            example: AI generated text
            type: string
        type: object
      title: Note
    generateResponseForRawNote_request:
      properties:
        prompt:
          enum:
          - summarize
          - listAsBulletsPoints
          title: prompt
          type: string
      title: generateResponseForRawNote_request
      type: object
    transcribeAudioForNote_request:
      properties:
        file:
          format: binary
          type: string
      type: object
